clusters:
- name: argocd-cluster
  destinationServer: https://kubernetes.default.svc
  apps:
    prometheus:
      enabled: false
      version: "9.7.4"

    sampleApp:
      enabled: true
      branch: HEAD

- name: scaleout-cluster
  destinationServer: https://3BB503852C7115148AAA16087C6736C5.gr7.ap-northeast-1.eks.amazonaws.com
  apps:
    prometheus:
      enabled: false
      version: "9.7.4"
    sampleApp:
      enabled: true
      branch: HEAD
